from qa_runtime_loader import runtime_sources, runtime_styles
from pathlib import Path
from playwright.sync_api import sync_playwright
BASE=Path(__file__).resolve().parents[1];WEB=BASE/'GitHub';CSS=runtime_styles(WEB)
SCRIPTS=['logical-move.js','reasoning-view.js','reasoning-presentation.js','pedagogy-metadata.js','nonogram-logic.js','difficulty-rating.js','nonogram-difficulty.js','session-core.js','game-session-adapters.js','game-ui-adapters.js','nonogram-reasoning-presentation.js','nonogram-pedagogy.js','nonogram-ui.js']
HTML='''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main id="app"></main><div id="live"></div><section id="tutorText" aria-live="polite"></section></body></html>'''
def setup(page):
    page.set_content(HTML);page.add_style_tag(content=CSS)
    for src in runtime_sources(WEB,include=SCRIPTS):page.add_script_tag(content=src)
    page.evaluate("""()=>{const A=QuadludGameSessionAdapters.nonogram;const puzzle={game:'nonogram',rows:5,cols:5,rowClues:[[5],[],[5],[],[5]],colClues:[[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]]};window.source=A.createGeneratedSession('easy',{game:'nonogram',puzzle,unique:true,generated:true,seed:'tutor',generatorVersion:1,fingerprint:'qfp1-tutor',generationStats:{},difficultyProfile:{difficulty:'easy'},validationState:{solutionGrid:Array.from({length:5},(_,r)=>Array(5).fill(r%2===0?1:0)),privateTrace:['hidden']}});window.sourceBefore=JSON.stringify(source);window.tutor=QuadludNonogramPedagogy.createTutor({now:(()=>{let n=2000;return()=>n++})()});window.walk=tutor.start(source,{fromRoot:false});const q=s=>document.querySelector(s),coord=(r,c)=>`Ligne ${r+1}, colonne ${c+1}`;function setCell(el,r,c,label){el.setAttribute('role','gridcell');el.setAttribute('aria-rowindex',r+1);el.setAttribute('aria-colindex',c+1);el.setAttribute('aria-label',label)}function setupGrid(board){board.setAttribute('role','grid');[...board.children].forEach((x,i)=>x.tabIndex=i?-1:0)}function shell(name,subtitle,diff,content){q('#app').innerHTML=`<section class="panel">${content}</section>`}window.ui=QuadludNonogramUI.createAdapter({document,query:q,shell,getCurrent:()=>walk.work,isPaused:()=>false,a11ySetupGrid:setupGrid,a11yAnnounce:t=>q('#live').textContent=t,a11yCoord:coord,a11ySetCell:setCell,applyLogicalMove:()=>{},maybeAutoFinish:()=>false,haptic:()=>{}});ui.render(walk.work);window.preview=tutor.preview(walk);ui.focusEntities(preview.presentation.focus);q('#tutorText').textContent=preview.levels.map(x=>x.text).join(' | ');}""")
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox']);ctx=browser.new_context(viewport={'width':390,'height':844},locale='fr-FR',is_mobile=True,has_touch=True);page=ctx.new_page();setup(page)
    before=page.evaluate("""()=>({sourceUnchanged:JSON.stringify(source)===sourceBefore,workState:walk.work.state.map(r=>[...r]),nodes:Object.keys(walk.work.moveHistory.nodes).length,moves:walk.moves.length,levels:preview.levels.map(x=>x.id),technique:preview.presentation.technique,target:document.querySelectorAll('.ng-focus-target').length,premise:document.querySelectorAll('.ng-focus-premise').length,context:document.querySelectorAll('.ng-focus-context').length,text:document.querySelector('#tutorText').textContent,hidden:JSON.stringify(preview).includes('solutionGrid')||JSON.stringify(preview).includes('validationState')})""")
    assert before['sourceUnchanged'] and before['nodes']==1 and before['moves']==0 and all(v==0 for row in before['workState'] for v in row),before;assert before['levels']==['where','technique','why','move'] and before['technique']=='N_EXACT_FIT' and before['target']==5 and before['premise']>=1 and before['context']>=1 and before['text'].strip() and not before['hidden'],before
    after=page.evaluate("""()=>{const step=tutor.applyPreview(walk,preview);ui.draw();return {state:walk.work.state.map(r=>[...r]),nodes:Object.keys(walk.work.moveHistory.nodes).length,moves:walk.moves.length,sourceUnchanged:JSON.stringify(source)===sourceBefore,historyValid:tutor.history.historyValid(walk.work)}}""");assert after['state'][0]==[1,1,1,1,1] and after['nodes']==2 and after['moves']==1 and after['sourceUnchanged'] and after['historyValid'],after
    final=page.evaluate("""()=>{let guard=0;while(!walk.done&&!walk.stalled&&guard++<50)tutor.next(walk);ui.draw();return {done:walk.done,stalled:walk.stalled,moves:walk.moves.length,nodes:Object.keys(walk.work.moveHistory.nodes).length,solved:NonogramLogic.isSolved(walk.work.puzzle,walk.work.state),sourceUnchanged:JSON.stringify(source)===sourceBefore,hidden:JSON.stringify(walk).includes('solutionGrid')||JSON.stringify(walk).includes('validationState')}}""");assert final=={'done':True,'stalled':False,'moves':5,'nodes':6,'solved':True,'sourceUnchanged':True,'hidden':False},final;ctx.close();browser.close()
print('stage32.8 nonogram tutor browser: OK')
