from qa_runtime_loader import runtime_sources, runtime_styles
from pathlib import Path
from playwright.sync_api import sync_playwright
BASE=Path(__file__).resolve().parents[1];WEB=BASE/'GitHub';CSS=runtime_styles(WEB)
SCRIPTS=['logical-move.js','reasoning-view.js','reasoning-presentation.js','pedagogy-metadata.js','nonogram-logic.js','difficulty-rating.js','nonogram-difficulty.js','session-core.js','game-session-adapters.js','game-ui-adapters.js','nonogram-reasoning-presentation.js','nonogram-pedagogy.js','nonogram-ui.js']
HTML='''<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><main id="app"></main><div id="live"></div></body></html>'''
def setup(page):
    page.set_content(HTML);page.add_style_tag(content=CSS)
    for src in runtime_sources(WEB,include=SCRIPTS):page.add_script_tag(content=src)
    page.evaluate("""()=>{const A=QuadludGameSessionAdapters.nonogram;const puzzle={game:'nonogram',rows:5,cols:5,rowClues:[[5],[],[5],[],[5]],colClues:[[1,1,1],[1,1,1],[1,1,1],[1,1,1],[1,1,1]]};window.current=A.createGeneratedSession('easy',{game:'nonogram',puzzle,unique:true,generated:true,seed:'coach',generatorVersion:1,fingerprint:'qfp1-coach',generationStats:{},difficultyProfile:{difficulty:'easy'},validationState:{solutionGrid:Array.from({length:5},(_,r)=>Array(5).fill(r%2===0?1:0))}});const q=s=>document.querySelector(s),coord=(r,c)=>`Ligne ${r+1}, colonne ${c+1}`;function setCell(el,r,c,label){el.setAttribute('role','gridcell');el.setAttribute('aria-rowindex',r+1);el.setAttribute('aria-colindex',c+1);el.setAttribute('aria-label',label)}function setupGrid(board){board.setAttribute('role','grid');[...board.children].forEach((x,i)=>x.tabIndex=i?-1:0)}function shell(name,subtitle,diff,content){q('#app').innerHTML=`<section class="panel">${content}</section>`}window.ui=QuadludNonogramUI.createAdapter({document,query:q,shell,getCurrent:()=>current,isPaused:()=>false,a11ySetupGrid:setupGrid,a11yAnnounce:t=>q('#live').textContent=t,a11yCoord:coord,a11ySetCell:setCell,applyLogicalMove:()=>{},maybeAutoFinish:()=>false,haptic:()=>{},gridCoordinates:QuadludGameUiAdapters.GridCoordinates});ui.render(current);const rv=QuadludReasoningView.defineReasoningView(A.reasoningView(current));window.coach=QuadludNonogramPedagogy.createCoach();window.hint=coach.next(rv);ui.focusEntities(hint.presentation.focus);}""")
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox']);ctx=browser.new_context(viewport={'width':390,'height':844},locale='fr-FR',is_mobile=True,has_touch=True);page=ctx.new_page();setup(page)
    data=page.evaluate("""()=>({status:hint.status,levels:hint.levels.map(x=>x.id),texts:hint.levels.map(x=>x.text),technique:hint.presentation.technique,focus:hint.presentation.focus.map(x=>[x.entity.kind,x.entity.id,x.role]),targets:hint.presentation.action.move.effects.map(x=>x.target.id),premiseEls:document.querySelectorAll('.ng-focus-premise').length,contextEls:document.querySelectorAll('.ng-focus-context').length,targetEls:document.querySelectorAll('.ng-focus-target').length,hidden:JSON.stringify(hint).includes('solutionGrid')||JSON.stringify(hint).includes('validationState')})""")
    assert data['status']=='deduction' and data['levels']==['where','technique','why','move'] and data['technique']=='N_EXACT_FIT',data;assert any(k=='row' for k,_,_ in data['focus']) and any(k=='clue' for k,_,_ in data['focus']),data;assert data['targetEls']==5 and data['premiseEls']>=1 and data['contextEls']>=1 and not data['hidden'],data;assert data['targets']==[f'r0c{i}' for i in range(5)],data;human=' | '.join(data['texts']);assert 'A1' in human and 'A5' in human and 'r0c0' not in human and 'r0c4' not in human,human;ctx.close();browser.close()
print('stage32.7 nonogram coach browser: OK')
